import { Router, Request, Response, NextFunction } from 'express';
import crypto from 'crypto';
import bcrypt from 'bcrypt';
import sql from 'mssql';
import net from 'net';
import rateLimit from 'express-rate-limit';
import { getPortalConnection, getGameConnection } from './db';
import { encryptAES, decryptAES } from './utils/crypto';
import { verifyTurnstile } from './turnstile';

const router = Router();
const COOKIE = 'upt_admin_sid';
const PRE_COOKIE = 'upt_admin_pre';
const TTL = 30 * 60 * 1000;
const ROLE_PERMISSIONS: Record<string,string[]> = {
  SUPER_ADMIN:['players.read','characters.read','server.read','audit.read','admins.manage','backups.create','backups.restore'],
  ADMIN:['players.read','characters.read','server.read','audit.read'], GM:['players.read','characters.read','server.read'],
  SUPORTE:['players.read','characters.read'], FINANCEIRO:[], CONTEUDO:['server.read'], AUDITOR:['server.read','audit.read']
};
type AdminRequest = Request & { admin?: { id:number; username:string; role:string; permissions:string[] } };
const limiter=rateLimit({windowMs:15*60*1000,max:10,message:{error:{code:'UPT-ADM-RATE',message:'Muitas tentativas. Aguarde e tente novamente.'}}});
const hash=(v:string)=>crypto.createHash('sha256').update(v).digest('hex');
const token=()=>crypto.randomBytes(32).toString('hex');
const cookieOptions={httpOnly:true,secure:process.env.NODE_ENV==='production',sameSite:'strict' as const,path:'/',maxAge:TTL};
const base32='ABCDEFGHIJKLMNOPQRSTUVWXYZ234567';
function base32Encode(data:Buffer){let bits='';for(const b of data)bits+=b.toString(2).padStart(8,'0');let out='';for(let i=0;i<bits.length;i+=5)out+=base32[parseInt(bits.slice(i,i+5).padEnd(5,'0'),2)];return out;}
function base32Decode(value:string){let bits='';for(const c of value.replace(/=+$/,'').toUpperCase()){const i=base32.indexOf(c);if(i<0)throw new Error('TOTP inválido');bits+=i.toString(2).padStart(5,'0');}const bytes=[];for(let i=0;i+8<=bits.length;i+=8)bytes.push(parseInt(bits.slice(i,i+8),2));return Buffer.from(bytes);}
function totp(secret:string,offset=0){const step=Math.floor(Date.now()/30000)+offset;const b=Buffer.alloc(8);b.writeBigInt64BE(BigInt(step));const h=crypto.createHmac('sha1',base32Decode(secret)).update(b).digest();const o=h[h.length-1]&15;return (((h.readUInt32BE(o)&0x7fffffff)%1000000)+'').padStart(6,'0');}
function verifyTotp(secret:string,code:string){return [-1,0,1].some(o=>{const a=Buffer.from(totp(secret,o));const b=Buffer.from(String(code));return a.length===b.length&&crypto.timingSafeEqual(a,b);});}
async function audit(adminId:number|null,action:string,result:string,req:Request,target=''){const p=await getPortalConnection();await p.request().input('id',sql.Int,adminId).input('action',sql.VarChar,action).input('target',sql.VarChar,target).input('result',sql.VarChar,result).input('ip',sql.VarChar,req.ip||'unknown').query('INSERT INTO AdminAuditLog(AdminUserID,Action,Target,Result,IPAddress) VALUES(@id,@action,@target,@result,@ip)');}
async function createSession(res:Response,req:Request,id:number,cookie=COOKIE,mfa=true){const raw=token();const p=await getPortalConnection();await p.request().input('h',sql.Char,hash(raw)).input('id',sql.Int,id).input('mfa',sql.Bit,mfa).input('exp',sql.DateTime2,new Date(Date.now()+TTL)).input('ip',sql.VarChar,req.ip||'unknown').input('ua',sql.VarChar,req.headers['user-agent']||'unknown').query('INSERT INTO AdminSessions(TokenHash,AdminUserID,MfaVerified,ExpiresAt,IPAddress,UserAgent) VALUES(@h,@id,@mfa,@exp,@ip,@ua)');res.cookie(cookie,raw,cookieOptions);}
async function requireAdmin(req:AdminRequest,res:Response,next:NextFunction){const raw=req.cookies?.[COOKIE];if(!raw)return res.status(401).json({error:{code:'UPT-ADM-401',message:'Autenticação administrativa necessária.'}});const p=await getPortalConnection();const q=await p.request().input('h',sql.Char,hash(raw)).query('SELECT u.ID,u.Username,u.Role FROM AdminSessions s JOIN AdminUsers u ON u.ID=s.AdminUserID WHERE s.TokenHash=@h AND s.RevokedAt IS NULL AND s.MfaVerified=1 AND s.ExpiresAt>SYSUTCDATETIME() AND u.Active=1');if(!q.recordset.length)return res.status(401).json({error:{code:'UPT-ADM-401',message:'Sessão expirada.'}});const u=q.recordset[0];req.admin={id:u.ID,username:u.Username,role:u.Role,permissions:ROLE_PERMISSIONS[u.Role]||[]};next();}
function permit(permission:string){return(req:AdminRequest,res:Response,next:NextFunction)=>req.admin?.permissions.includes(permission)?next():res.status(403).json({error:{code:'UPT-ADM-403',message:'Permissão insuficiente.'}});}
router.post('/login',limiter,async(req,res)=>{if(!await verifyTurnstile(req,'admin_login'))return res.status(400).json({error:{code:'UPT-CAPTCHA-001',message:'Confirme a verificação de segurança e tente novamente.'}});const username=String(req.body.username||'').trim();const password=String(req.body.password||'');const p=await getPortalConnection();const q=await p.request().input('u',sql.VarChar,username).query('SELECT TOP 1 * FROM AdminUsers WHERE Username=@u AND Active=1');const u=q.recordset[0];const unlocked=Boolean(u&&(!u.LockedUntil||new Date(u.LockedUntil)<=new Date()));const valid=Boolean(unlocked&&await bcrypt.compare(password,u.PasswordHash));if(!valid){if(u)await p.request().input('id',sql.Int,u.ID).query('UPDATE AdminUsers SET FailedAttempts=FailedAttempts+1,LockedUntil=CASE WHEN FailedAttempts>=4 THEN DATEADD(minute,15,SYSUTCDATETIME()) ELSE LockedUntil END WHERE ID=@id');await audit(u?.ID||null,'ADMIN_LOGIN','DENIED',req);return res.status(401).json({error:{code:'UPT-ADM-LOGIN',message:'Credenciais ou segundo fator inválidos.'}});}await p.request().input('id',sql.Int,u.ID).query('UPDATE AdminUsers SET FailedAttempts=0,LockedUntil=NULL WHERE ID=@id');if(u.ForcePasswordChange){await createSession(res,req,u.ID,PRE_COOKIE,false);await audit(u.ID,'ADMIN_PASSWORD_OK','FORCE_PASSWORD_CHANGE',req);return res.json({forcePasswordChange:true});}await createSession(res,req,u.ID,PRE_COOKIE,false);await audit(u.ID,'ADMIN_PASSWORD_OK','PENDING_MFA',req);res.json({mfaRequired:true,enrollmentRequired:!u.MfaEnabled});});
router.post('/mfa/enroll',async(req,res)=>{const raw=req.cookies?.[PRE_COOKIE];if(!raw)return res.status(401).json({error:{message:'Pré-autenticação necessária.'}});const p=await getPortalConnection();const q=await p.request().input('h',sql.Char,hash(raw)).query('SELECT u.ID,u.Username,u.TotpSecretEncrypted FROM AdminSessions s JOIN AdminUsers u ON u.ID=s.AdminUserID WHERE s.TokenHash=@h AND s.RevokedAt IS NULL AND s.ExpiresAt>SYSUTCDATETIME()');if(!q.recordset.length)return res.status(401).json({error:{message:'Pré-autenticação expirada.'}});const u=q.recordset[0];let secret=u.TotpSecretEncrypted?decryptAES(u.TotpSecretEncrypted,process.env.FIELD_ENCRYPTION_KEY||''):base32Encode(crypto.randomBytes(20));if(!u.TotpSecretEncrypted)await p.request().input('id',sql.Int,u.ID).input('s',sql.VarChar,encryptAES(secret,process.env.FIELD_ENCRYPTION_KEY||'')).query('UPDATE AdminUsers SET TotpSecretEncrypted=@s WHERE ID=@id');res.json({secret,otpauth:`otpauth://totp/UniversoPT:${encodeURIComponent(u.Username)}?secret=${secret}&issuer=UniversoPT`});});
router.post('/mfa/verify',limiter,async(req,res)=>{const raw=req.cookies?.[PRE_COOKIE];if(!raw)return res.status(401).json({error:{message:'Pré-autenticação necessária.'}});const p=await getPortalConnection();const q=await p.request().input('h',sql.Char,hash(raw)).query('SELECT u.ID,u.TotpSecretEncrypted FROM AdminSessions s JOIN AdminUsers u ON u.ID=s.AdminUserID WHERE s.TokenHash=@h AND s.RevokedAt IS NULL AND s.ExpiresAt>SYSUTCDATETIME()');const u=q.recordset[0];if(!u?.TotpSecretEncrypted||!verifyTotp(decryptAES(u.TotpSecretEncrypted,process.env.FIELD_ENCRYPTION_KEY||''),String(req.body.code||'')))return res.status(401).json({error:{message:'Credenciais ou segundo fator inválidos.'}});await p.request().input('id',sql.Int,u.ID).query('UPDATE AdminUsers SET MfaEnabled=1 WHERE ID=@id');await createSession(res,req,u.ID);res.clearCookie(PRE_COOKIE,cookieOptions);await audit(u.ID,'ADMIN_LOGIN','SUCCESS',req);res.json({success:true});});
router.post('/change-password',limiter,async(req,res)=>{const raw=req.cookies?.[PRE_COOKIE];if(!raw)return res.status(401).json({error:{message:'Pré-autenticação necessária.'}});const p=await getPortalConnection();const q=await p.request().input('h',sql.Char,hash(raw)).query('SELECT u.ID,u.Username,u.ForcePasswordChange FROM AdminSessions s JOIN AdminUsers u ON u.ID=s.AdminUserID WHERE s.TokenHash=@h AND s.RevokedAt IS NULL AND s.ExpiresAt>SYSUTCDATETIME()');const u=q.recordset[0];if(!u)return res.status(401).json({error:{message:'Sessão expirada.'}});const newPass=String(req.body.newPassword||'');const confirm=String(req.body.confirmPassword||'');if(newPass!==confirm)return res.status(400).json({error:{message:'As senhas não coincidem.'}});if(newPass.length<12)return res.status(400).json({error:{message:'A senha deve ter pelo menos 12 caracteres.'}});if(!/[a-z]/.test(newPass)||!/[A-Z]/.test(newPass)||!/[0-9]/.test(newPass)||!/[^a-zA-Z0-9]/.test(newPass))return res.status(400).json({error:{message:'A senha deve conter letras maiúsculas, minúsculas, números e caracteres especiais.'}});const newHash=await bcrypt.hash(newPass,12);await p.request().input('id',sql.Int,u.ID).input('ph',sql.VarChar,newHash).query('UPDATE AdminUsers SET PasswordHash=@ph,ForcePasswordChange=0,PasswordChangedAt=SYSUTCDATETIME() WHERE ID=@id');await p.request().input('h',sql.Char,hash(raw)).query('UPDATE AdminSessions SET RevokedAt=SYSUTCDATETIME() WHERE TokenHash=@h');res.clearCookie(PRE_COOKIE,cookieOptions);await audit(u.ID,'ADMIN_PASSWORD_CHANGE','SUCCESS',req);res.json({success:true,message:'Senha alterada. Faça login novamente.'});});
router.post('/logout',requireAdmin,async(req:AdminRequest,res)=>{const raw=req.cookies?.[COOKIE];const p=await getPortalConnection();await p.request().input('h',sql.Char,hash(raw)).query('UPDATE AdminSessions SET RevokedAt=SYSUTCDATETIME() WHERE TokenHash=@h');res.clearCookie(COOKIE,cookieOptions);await audit(req.admin!.id,'ADMIN_LOGOUT','SUCCESS',req);res.json({success:true});});
function portOpen(port:number){return new Promise<boolean>(resolve=>{const s=net.createConnection({host:'127.0.0.1',port,timeout:1200},()=>{s.destroy();resolve(true)});s.on('error',()=>resolve(false));s.on('timeout',()=>{s.destroy();resolve(false)});});}
router.get('/status',requireAdmin,permit('server.read'),async(_req,res)=>{let portalDb=false,gameDb=false;try{await(await getPortalConnection()).request().query('SELECT 1');portalDb=true}catch{}try{await(await getGameConnection()).request().query('SELECT 1');gameDb=true}catch{}res.json({portal:'Online',api:'Online',portalDatabase:portalDb?'Online':'Offline',gameDatabase:gameDb?'Online':'Offline',loginServer:(await portOpen(10009))?'Online':'Offline',gameServer:(await portOpen(30010))?'Online':'Offline',updatedAt:new Date().toISOString()});});
router.post('/server/broadcast',requireAdmin,permit('server.broadcast'),(_req,res)=>res.status(501).json({error:{code:'UPT-ADM-NYI',message:'Operação indisponível: canal administrativo autenticado não encontrado.'}}));
export default router;
